exports_files([
    "workspace.bzl",
])

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
bzl_library(
    name = "errorprone-rules",
    srcs = ["workspace.bzl"],
    visibility = ["//visibility:public"],
)
