load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "workspace.bzl",
])

bzl_library(
    name = "errorprone-rules",
    srcs = ["workspace.bzl"],
    visibility = ["//visibility:public"],
)
