load("@rules_jvm_external//:defs.bzl", "artifact")

java_library(
    name = "mockito",
    testonly = True,
    visibility = ["//java:__subpackages__"],
    exports = [
        artifact("org.mockito:mockito-core"),
    ],
)
