exports_files([
    "rules.bzl",
])

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
bzl_library(
    name = "javadoc-rules",
    srcs = ["rules.bzl"],
    visibility = ["//visibility:public"],
)
