load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "rules.bzl",
])

bzl_library(
    name = "javadoc-rules",
    srcs = ["rules.bzl"],
    visibility = ["//visibility:public"],
)
